/** Route path prefixes used for navigation and page detection */

export const ROUTES = {
  AUTH: '/auth/',
  AUTH_LOGIN: '/auth/login',
  AUTH_REGISTER: '/auth/register',
  AUTH_FORGOT_PASSWORD: '/auth/forgot-password',
  AUTH_MFA: '/auth/mfa',
  MESSAGING: '/messaging',
  MESSAGING_CHAT: (id: string) => `/messaging/${id}`,
  PROFILE: '/profile',
  PROFILE_SETTINGS: '/profile/settings',
  PROFILE_NOTIFICATIONS: '/profile/notifications',
  PROFILE_ID_VERIFICATION: '/profile/id-verification',
  ADMIN: '/admin',
  ADMIN_USERS: '/admin/users',
  ADMIN_LISTINGS: '/admin/listings',
  ADMIN_SHORTS: '/admin/shorts',
  ADMIN_SHORTS_ANALYTICS: '/admin/shorts-analytics',

  ADMIN_ID_VERIFICATIONS: '/admin/id-verifications',
  ADMIN_ACTIVITY: '/admin/activity',
  ADMIN_PAYMENTS: '/admin/payments',
  ADMIN_PACKAGES: '/admin/packages',
  ADMIN_PACKAGES_LISTINGS: '/admin/packages/listings',
  ADMIN_PACKAGES_SHORTS: '/admin/packages/shorts',
  ADMIN_PACKAGES_PURCHASES: '/admin/packages/purchases',
  ADMIN_NOTIFICATIONS: '/admin/notifications',
  ADMIN_CATEGORIES: '/admin/categories',
  ADMIN_LOCATIONS: '/admin/locations',
  ADMIN_BRANDS: '/admin/brands',
  ADMIN_VEHICLES: '/admin/vehicles',
  ADMIN_DELETION_REASONS: '/admin/deletion-reasons',
  ADMIN_REJECTION_REASONS: '/admin/rejection-reasons',
  ADMIN_EXPERIMENTS: '/admin/experiments',
  SEARCH: '/search',
  LISTINGS: '/listings',
  LISTINGS_CREATE: '/listings/create',
  LISTINGS_MY: '/listings/my',
  FAVORITES: '/favorites',
  PACKAGES: '/packages',
  PACKAGES_MY: '/packages/my',
  CATEGORIES: '/categories',
  SHORTS: '/shorts',
  SHORTS_UPLOAD: '/shorts/upload',
  SHORTS_MY: '/shorts/my',
  SHORTS_EDIT: (id: string) => `/shorts/${id}/edit`,
  HOME: '/',

  SELLER: (id: string) => `/seller/${id}`,

  // Static pages
  PAGES_ABOUT: '/pages/about',
  PAGES_CAREERS: '/pages/careers',
  PAGES_PRESS: '/pages/press',
  PAGES_TRUST_SAFETY: '/pages/trust-safety',
  PAGES_SELLING_TIPS: '/pages/selling-tips',
  PAGES_CONTACT: '/pages/contact',
  PAGES_TERMS: '/pages/terms',
  PAGES_PRIVACY: '/pages/privacy',
  PAGES_COOKIES: '/pages/cookies',
} as const;
